rpp_test/rpp_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quotes.views import QuoteDetailView, QuoteCreateView, QuoteUpdateView, QuoteDeleteView, QuoteListView
from parts.views import PartNumberDetailView, PartNumberCreateView, PartNumberUpdateView, PartNumberDeleteView
from retention_analyst.views import RetentionAnalystDetailView, RetentionAnalystCreateView, RetentionAnalystUpdateView, RetentionAnalystDeleteView
from sales.views import SalesAccountCreateView, SalesAccountDeleteView, SalesAccountUpdateView, SalesDetailView, SalesContractListView, SalesClientListView
from manufacturers.views import ManufacturerCreateView, ManufacturerUpdateView, ManufacturerDeleteView
from rpp_test_tables.views import passthru, ClientDetailView, ClientUpdateView, ClientCreateView, \
                                  AdminDashboard, ContractUpdateView, ProductUpdateView, ProductDetailView, ProductCreateView, \
                                  VendorCreateView, VendorUpdateView, VendorDeleteView, UserCreateView, ProductListView, ClientListView, \
                                  ContractListView, PartListView, ManufacturerListView, RetentionAnalystListView, SalesListView, VendorListView, \
                                  ContractDetailView, NewContractCreateView, ClientDetailContactInfoView, SalesContractCreateView, ContractNumberDetailView, ContractNumberListView, \
                                  NewClientDashboard
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', auth_views.login, name='login'),
    url(r'^new-dashboard-demo/$', NewClientDashboard.as_view(), name='new_client_dashboard'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^passthru/$', passthru, name='passthru_view'),
    url(r'^admin-dashboard/$', user_passes_test(lambda u: u.is_superuser)(
AdminDashboard.as_view()), name='admin_dashboard'),
    url(r'^contract-number/(?P<pk>\d+)/$', ContractNumberDetailView.as_view(), name='contract_number_detail_view'),
    url(r'^contract-number/list/$', ContractNumberListView.as_view(), name='contract_number_list_view'),
    url(r'^client/(?P<pk>\d+)/contract/$', NewContractCreateView.as_view(), name='new_contract_create_view'),
    url(r'^client-detail/(?P<pk>\d+)/$', ClientDetailView.as_view(), name='client_detail_view'),
    url(r'^client/(?P<pk>\d+)/update/$', ClientUpdateView.as_view(), name='client_update_view'),
    url(r'^client-create/$', ClientCreateView.as_view(), name='client_create_view'),
    url(r'^client-list/$', ClientListView.as_view(), name='client_list_view'),
    url(r'^sales/(?P<pk>\d+)/clients/$', SalesClientListView.as_view(), name='sales_client_list_view'),
    url(r'^client-detail/(?P<pk>\d+)/contact-info/$', ClientDetailContactInfoView.as_view(), name='client_contact_view'),
    url(r'^sales/client/(?P<pk>\d+)/contract$', SalesContractCreateView.as_view(), name='sales_contract_create_view'),
    url(r'^contract/(?P<pk>\d+)/$', ContractDetailView.as_view(), name='contract_detail_view'),
    url(r'^contract/(?P<pk>\d+)/update/$', ContractUpdateView.as_view(), name='contract_update_view'),
    url(r'^contract-list/(?P<category>\w+)/$', ContractListView.as_view(), name='contract_list_view'),
    url(r'^product/(?P<pk>\d+)/detail/$', ProductDetailView.as_view(), name='product_detail_view'),
    url(r'^product/(?P<pk>\d+)/update/$', ProductUpdateView.as_view(), name='product_update_view'),
    url(r'^product-list/$', ProductListView.as_view(), name='product_list_view'),
    url(r'^client-detail/(?P<pk>\d+)/product/$', ProductCreateView.as_view(), name='product_create_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/$', RetentionAnalystDetailView.as_view(), name='retention_analyst_detail'),
    url(r'^retention-analyst-create/$', RetentionAnalystCreateView.as_view(), name='retention_analyst_create_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/edit$', RetentionAnalystUpdateView.as_view(), name='retention_analyst_update_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/delete$', RetentionAnalystDeleteView.as_view(), name='retention_analyst_delete_view'),
    url(r'^retention-analyst-list/$', RetentionAnalystListView.as_view(), name='retention_analyst_list_view'),
    url(r'^vendor-create/$', VendorCreateView.as_view(), name='vendor_create_view'),
    url(r'^vendor/(?P<pk>\d+)/update/$', VendorUpdateView.as_view(), name='vendor_update_view'),
    url(r'^vendor/(?P<pk>\d+)/delete/$', VendorDeleteView.as_view(), name='vendor_delete_view'),
    url(r'^vendor-list/$', VendorListView.as_view(), name='vendor_list_view'),
    url(r'^manufacturer-create/$', ManufacturerCreateView.as_view(), name='manufacturer_create_view'),
    url(r'^manufacturer/(?P<pk>\d+)/update/$', ManufacturerUpdateView.as_view(), name='manufacturer_update_view'),
    url(r'^manufacturer/(?P<pk>\d+)/$', ManufacturerDeleteView.as_view(), name='manufacturer_delete_view'),
    url(r'^manufacturer-list/$', ManufacturerListView.as_view(), name='manufacturer_list_view'),
    url(r'^sales-agent-create/$', SalesAccountCreateView.as_view(), name='sales_account_create_view'),
    url(r'^sales/(?P<pk>\d+)/update/$', SalesAccountUpdateView.as_view(), name='salesaccount_update_view'),
    url(r'^sales/(?P<pk>\d+)/delete$', SalesAccountDeleteView.as_view(), name='salesaccount_delete_view'),
    url(r'^sales/(?P<pk>\d+)/$', SalesDetailView.as_view(), name='salesaccount_detail_view'),
    url(r'^sales-account-list/$', SalesListView.as_view(), name='salesaccount_list_view'),
    url(r'^sales/(?P<pk>\d+)/contracts/(?P<category>\w+)/$', SalesContractListView.as_view(), name='sales_contract_list_view'),
    url(r'^part-create/$', PartNumberCreateView.as_view(), name='part_create_view'),
    url(r'^part/(?P<pk>\d+)/edit/$', PartNumberUpdateView.as_view(), name='part_update_view'),
    url(r'^part/(?P<pk>\d+)/$', PartNumberDetailView.as_view(), name='part_detail_view'),
    url(r'^part/(?P<pk>\d+)/delete/$', PartNumberDeleteView.as_view(), name='part_delete_view'),
    url(r'^part-list/$', PartListView.as_view(), name='part_list_view'),
    url(r'^quote-create/(?P<pk>\d+)/$', QuoteCreateView.as_view(), name='quote_create_view'),
    url(r'^quote-create/$', QuoteCreateView.as_view(), name='quote_create_view_new'),
    url(r'^quote/(?P<pk>\d+)/edit/$', QuoteUpdateView.as_view(), name='quote_update_view'),
    url(r'^quote/(?P<pk>\d+)/delete/$', QuoteDeleteView.as_view(), name='quote_delete_view'),
    url(r'^quote/(?P<pk>\d+)/$', QuoteDetailView.as_view(), name='quote_detail_view'),
    url(r'^quote-list/$', QuoteListView.as_view(), name='quote_list_view'),
    url(r'^rentention-analyst/(?P<reta>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_reta'),
    url(r'^client/(?P<client>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_client'),
    url(r'^sales/(?P<agent>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_sales'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rpp_test/rpp_test_tables/models.py
from django.db import models
from datetime import datetime, timedelta, timezone
from django.utils import timezone
import pytz
from simple_history.models import HistoricalRecords

class SalesAccount(models.Model):
    user = models.OneToOneField('auth.User')
    name = models.CharField(max_length=144)
    retention_analyst = models.ForeignKey('RetentionAnalyst')
    vendors = models.ManyToManyField('Vendor')
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @property
    def recent_sales(self):
        return [x for x in self.contract_set.all() if x.start_date > timezone.now().date() + timedelta(days=7)]

class Client(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    website = models.CharField(max_length=200)
    web_admin = models.CharField(max_length=100,null=True,blank=True)
    web_admin_cell = models.CharField(max_length=100,null=True,blank=True)
    correspondence_signature = models.CharField(max_length=100)
    correspondence_signature_title = models.CharField(max_length=100)
    correspondence_phone = models.CharField(max_length=100)
    correspondence_contact_one = models.CharField(max_length=100)
    correspondence_contact_two = models.CharField(max_length=100,null=True,blank=True)
    correspondence_email = models.CharField(max_length=100)
    copy_emails_to_portal_list = models.IntegerField(null=True,blank=True)
    list_discount = models.CharField(max_length=100,null=True,blank=True)
    list_discount_international = models.CharField(max_length=100,null=True,blank=True)
    service_discount = models.CharField(max_length=100,null=True,blank=True)
    override_sales_tax = models.FloatField()
    discount_off_list_percent = models.FloatField()
    rate_factor_year = models.FloatField()
    rate_factor_two_year = models.FloatField()
    rate_factor_three_year = models.FloatField()
    residual_value = models.FloatField()
    aquisition_fee = models.FloatField()
    rate_factor_increase = models.FloatField(null=True,blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_changed_by = models.CharField(max_length=100,null=True,blank=True)
    email_address_salesperson = models.CharField(max_length=100,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey('auth.User')
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    @property
    def active_sales_agents(self):
        a = []
        for con in Contract.objects.filter(client=self):
            if con.sale_agent not in a:
                a.append(con.sale_agent)
        return a

    def active_analysts(self):
        a = []
        for agent in self.active_sales_agents:
            if agent.retention_analyst not in a:
                a.append(agent.retention_analyst)
        return a

class Vendor(models.Model):
    name = models.CharField(max_length=200)
    lead_product = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    website = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Manufacturer(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    phone = models.CharField(max_length=40)
    status = models.BooleanField(default=True)
    logo = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        if self.logo:
            return self.logo.url
        return "http://images.clipartpanda.com/animated-question-mark-for-powerpoint-1256186461796715642question-mark-icon.svg.hi.png"

class PartNumber(models.Model):
    manufacturer = models.ForeignKey(Manufacturer)
    desc = models.TextField()
    end_of_service = models.DateField()
    end_of_life = models.DateField()
    end_of_support = models.DateField()
    trade_value = models.FloatField(null=True,blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.manufacturer.name +  ' ' + self.desc

class Product(models.Model):
    part_num = models.ForeignKey(PartNumber)
    serial = models.CharField(max_length=200)
    client = models.ForeignKey(Client)
    purchase_date = models.DateField()
    disposal = models.DateField(null=True,blank=True)
    service_category = models.CharField(null=True,blank=True,max_length=100)
    price = models.FloatField()
    quantity_min = models.CharField(null=True,blank=True,max_length=100)
    quantity_max = models.CharField(null=True,blank=True,max_length=100)
    duration = models.CharField(null=True,blank=True,max_length=100)
    orderability = models.CharField(null=True,blank=True,max_length=100)
    item_identifier = models.CharField(null=True,blank=True,max_length=100)
    service_program = models.CharField(max_length=100)
    category_base_discount_name = models.CharField(null=True,blank=True,max_length=100)
    end_of_sale_date = models.DateField(null=True,blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.client.name + ' ' + self.part_num.desc
    @property
    def ninety(self):
        contracts = self.contract_set.all()
        for con in contracts:
            if timezone.now().date() + timedelta(days=90) > con.end_date:
                return True
        return False

    def not_trued(self):
        contracts = self.contract_set.all()
        if contracts.count() <= 1:
            return False
        end = contracts.first().end_date
        for con in contracts:
            if con.end_date != end:
                return True
        return False

    def serv_vendor(self):
        con = self.contract_set.all().first()
        return con.vendor

    def serv_end(self):
        x = self.contract_set.all().first().end_date
        for con in self.contract_set.all():
            if con.end_date < x:
                x = con.end_date
        return x

    def has_contract(self):
        if self.contract_set.all():
            return True
        return False

    def sales_agent(self):
        return self.sales_agents()[0]

    def sales_agents(self):
        return [cont.sale_agent for cont in self.contract_set.all()]

    def ret_analyst(self):
        return [agent.retention_analyst for agent in self.sales_agents()]


class Contract(models.Model):
    client = models.ForeignKey(Client)
    product = models.ForeignKey(Product)
    contract_number = models.ForeignKey('ContractNumber')
    serial = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.FloatField()
    vendor = models.ForeignKey(Vendor)
    sale_agent = models.ForeignKey(SalesAccount)
    commission = models.FloatField(default=0)
    service_level = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200)
    site_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=200)
    country = models.CharField(max_length=100)
    quantity = models.CharField(max_length=200)
    pak_num = models.CharField(max_length=200)
    smart_net_sku = models.CharField(max_length=200,null=True,blank=True)
    smark_net_desc = models.CharField(max_length=200,null=True,blank=True)
    annual_list_price = models.CharField(max_length=200,null=True,blank=True)
    trade_value = models.CharField(max_length=200,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.client.name + self.vendor.name + str(self.cost)

    @property
    def days_left(self):
        end = self.end_date
        td =  self.end_date - timezone.now().date()
        return td.days

    def ninety(self):
        if timezone.now().date() + timedelta(days=180) > self.end_date:
            return True
        return False

    def active(self):
        if self.end_date > timezone.now().date():
            return True
        return False

    def end_of_life(self):
        return self.product.part_num.end_of_life

    def end_of_service(self):
        return self.product.part_num.end_of_service


class ClientLogin(models.Model):
    client = models.ForeignKey(Client)
    time = models.DateTimeField(auto_now_add=True)

class SalesAccountLogin(models.Model):
    agent = models.ForeignKey(SalesAccount)
    time = models.DateTimeField(auto_now_add=True)

class AdminLogin(models.Model):
    admin = models.ForeignKey('auth.user')
    time = models.DateTimeField(auto_now_add=True)

# class AdminChange(model.Model):
#     admin = models.ForeignKey('auth.user')
#     time = models.DateTimeField(auto_now_add=True)

class RetentionAnalyst(models.Model):
    name = models.CharField(blank=True,null=True,max_length=100)
    email = models.CharField(max_length=100)
    user = models.OneToOneField('auth.User')

    def __str__(self):
        return str(self.name)

    @property
    def contract_count(self):
        return len([x for x in Contract.objects.all() if x.sale_agent.retention_analyst == self])


class ClientUser(models.Model):
    user = models.OneToOneField('auth.user')
    client = models.ForeignKey(Client)

rpp_test/sales/models.py
from django.db import models

# Create your models here.

rpp_test/templates/partials/new_dash/sales/admin/_detail.html
{% extends 'partials/new_dash/admin_base.html' %}
{% block content %}

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-8">
    <div class="topbox">
      <h4>Overview</h4>
      Name: {{ salesaccount.name }}<br>
      Logins: {{ object.salesaccountlogin_set.all.count }}<br>
      Analyst: <a href="{% url 'retention_analyst_detail' salesaccount.retention_analyst.id %}">{{ object.retention_analyst }}</a><br>
      Vendors:
      {% for ven in salesaccount.vendors.all %}
        {{ ven.name }}
      {% endfor %}<br>
      <h4>Activity</h4>
      Contracts Added in last week: {{ added_week.count }}<br>
      Contracts Added in last month: {{ added_month.count }}<br>
      <a href="{% url 'user_create_view_sales' salesaccount.id 1 %}"><button style="width:120px;" class="btn btn-warning" type="button" name="button">Add Login</button></a>
      <a href="{% url 'salesaccount_update_view' salesaccount.id %}"><button style="width:120px;" class="btn btn-success" type="button" name="button">Edit</button></a>
    </div>
  </div>
</div>
<h3 style="text-align:center;">Managed Contracts</h3>

<div style="font-size:18px;border-bottom:1px solid black;margin-bottom:10px;" class="row">
  <div class="col-md-2">Contract #</div>
  <div class="col-md-1">Client</div>
  <div class="col-md-1">Vendor</div>
  <div class="col-md-1">Agent</div>
  <div class="col-md-1">Analyst</div>
  <div class="col-md-6">
    <div class="col-md-3">End Date</div>
    <div class="col-md-3">End Life</div>
    <div class="col-md-3">End Service</div>
    <div class="col-md-3">End Support</div>
  </div>
</div>
{% for con in object.contract_set.all %}
<div class="con-item">
<a href="{% url 'contract_detail_view' con.id %}">
  <div class="row">
    <div class="col-md-2">{{ con.serial }}</div>
    <div class="col-md-1">{{ con.product.client }}</div>
    <div class="col-md-1">{{ con.vendor }}</div>
    <div class="col-md-1">{{ con.sale_agent }}</div>
    <div class="col-md-1">{{ con.sale_agent.retention_analyst }}</div>
    <div class="col-md-6">
      {% if con.ninety and not con.active %}
      <div style="color:red;" class="col-md-3">{{ con.end_date }}</div>
      {% elif con.ninety and con.active %}
      <div style="color:orange;" class="col-md-3">{{ con.end_date }}</div>
      {% else %}
      <div class="col-md-3">{{ con.end_date }}</div>
      {% endif %}
      <div class="col-md-3">{{ con.product.part_num.end_of_life }}</div>
      <div class="col-md-3">{{ con.product.part_num.end_of_service }}</div>
      <div class="col-md-3">{{ con.product.part_num.end_of_support }}</div>
    </div>
    <!-- <div class="col-md-2"></div>
    <div class="col-md-2">{{ con.product.part_num.end_of_life }}</div>
    <div class="col-md-2">{{ con.product.part_num.end_of_service }}</div> -->

  </div>
</a>
</div>
{% endfor %}




{% endblock %}

rpp_test/templates/partials/new_dash/sales/admin/_list.html
{% extends 'partials/new_dash/admin_base.html' %}
{% block content %}

<div style="font-size:18px;border-bottom:1px solid black;margin-bottom:10px;" class="row">
  <div class="col-md-2">Name</div>
  <div class="col-md-2">Retention Analyst</div>
  <div class="col-md-2">Contracts</div>
  <div class="col-md-2">Vendors</div>
</div>
{% for agent in object_list %}
<div class="con-item">
<a href="{% url 'salesaccount_detail_view' agent.id %}">
  <div class="row">
    <div class="col-md-2">{{ agent.name }}</div>
    <div class="col-md-2">{{ agent.retention_analyst }}</div>
    <div class="col-md-2">{{ agent.contract_set.all.count }}</div>
    <div class="col-md-6">
      {% for vendor in agent.vendors.all %}
        <div class="col-md-1">
          {{ vendor.name }}
        </div>
      {% endfor %}
    </div>
  </div>
</a>
</div>
{% endfor %}

{% endblock %}

rpp_test/templates/partials/new_dash/sales/admin/_update.html
{% extends 'partials/new_dash/admin_base.html' %}

{% block content %}

<div class="row bot-form">
  <div class="col-md-2"></div>
  <div class="col-md-8 form-box">
    <h3 style='text-align:center;'>Sales Agent Form</h3>
    <form class="" method="post">
      {% csrf_token %}
      <div class="row form-cat">
        <div class="col-md-3">Name:</div>
        <div class="col-md-9">{{ form.name }}</div>
      </div>
      <div class="row form-cat">
        <div class="col-md-3">Vendors:</div>
        <div class="col-md-9">{{ form.vendors }}</div>
      </div>
      <div class="row form-cat">
        <div class="col-md-3">Retention Agent:</div>
        <div class="col-md-9">{{ form.retention_analyst }}</div>
      </div>
      <div class="row form-cat">
        <div class="col-md-3"></div>
        <div class="col-md-9"><input class="btn" type="submit" name="" value="Submit"></div>
      </div>

    </form>
  </div>
</div>

{% endblock %}