rpp_test/rpp_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quotes.views import QuoteDetailView, QuoteCreateView, QuoteUpdateView, QuoteDeleteView, QuoteListView
from parts.views import PartNumberDetailView, PartNumberCreateView, PartNumberUpdateView, PartNumberDeleteView
from retention_analyst.views import RetentionAnalystDetailView, RetentionAnalystCreateView, RetentionAnalystUpdateView, RetentionAnalystDeleteView
from sales.views import SalesAccountCreateView, SalesAccountDeleteView, SalesAccountUpdateView, SalesDetailView, SalesContractListView, SalesClientListView
from manufacturers.views import ManufacturerCreateView, ManufacturerUpdateView, ManufacturerDeleteView
from rpp_test_tables.views import passthru, ClientDetailView, ClientUpdateView, ClientCreateView, \
                                  AdminDashboard, ContractUpdateView, ProductUpdateView, ProductDetailView, ProductCreateView, \
                                  VendorCreateView, VendorUpdateView, VendorDeleteView, UserCreateView, ProductListView, ClientListView, \
                                  ContractListView, PartListView, ManufacturerListView, RetentionAnalystListView, SalesListView, VendorListView, \
                                  ContractDetailView, NewContractCreateView, ClientDetailContactInfoView, SalesContractCreateView, ContractNumberDetailView, ContractNumberListView, \
                                  NewClientDashboard
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', auth_views.login, name='login'),
    url(r'^new-dashboard-demo/$', NewClientDashboard.as_view(), name='new_client_dashboard'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^passthru/$', passthru, name='passthru_view'),
    url(r'^admin-dashboard/$', user_passes_test(lambda u: u.is_superuser)(
AdminDashboard.as_view()), name='admin_dashboard'),
    url(r'^contract-number/(?P<pk>\d+)/$', ContractNumberDetailView.as_view(), name='contract_number_detail_view'),
    url(r'^contract-number/list/$', ContractNumberListView.as_view(), name='contract_number_list_view'),
    url(r'^client/(?P<pk>\d+)/contract/$', NewContractCreateView.as_view(), name='new_contract_create_view'),
    url(r'^client-detail/(?P<pk>\d+)/$', ClientDetailView.as_view(), name='client_detail_view'),
    url(r'^client/(?P<pk>\d+)/update/$', ClientUpdateView.as_view(), name='client_update_view'),
    url(r'^client-create/$', ClientCreateView.as_view(), name='client_create_view'),
    url(r'^client-list/$', ClientListView.as_view(), name='client_list_view'),
    url(r'^sales/(?P<pk>\d+)/clients/$', SalesClientListView.as_view(), name='sales_client_list_view'),
    url(r'^client-detail/(?P<pk>\d+)/contact-info/$', ClientDetailContactInfoView.as_view(), name='client_contact_view'),
    url(r'^sales/client/(?P<pk>\d+)/contract$', SalesContractCreateView.as_view(), name='sales_contract_create_view'),
    url(r'^contract/(?P<pk>\d+)/$', ContractDetailView.as_view(), name='contract_detail_view'),
    url(r'^contract/(?P<pk>\d+)/update/$', ContractUpdateView.as_view(), name='contract_update_view'),
    url(r'^contract-list/(?P<category>\w+)/$', ContractListView.as_view(), name='contract_list_view'),
    url(r'^product/(?P<pk>\d+)/detail/$', ProductDetailView.as_view(), name='product_detail_view'),
    url(r'^product/(?P<pk>\d+)/update/$', ProductUpdateView.as_view(), name='product_update_view'),
    url(r'^product-list/$', ProductListView.as_view(), name='product_list_view'),
    url(r'^client-detail/(?P<pk>\d+)/product/$', ProductCreateView.as_view(), name='product_create_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/$', RetentionAnalystDetailView.as_view(), name='retention_analyst_detail'),
    url(r'^retention-analyst-create/$', RetentionAnalystCreateView.as_view(), name='retention_analyst_create_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/edit$', RetentionAnalystUpdateView.as_view(), name='retention_analyst_update_view'),
    url(r'^retention-analyst/(?P<pk>\d+)/delete$', RetentionAnalystDeleteView.as_view(), name='retention_analyst_delete_view'),
    url(r'^retention-analyst-list/$', RetentionAnalystListView.as_view(), name='retention_analyst_list_view'),
    url(r'^vendor-create/$', VendorCreateView.as_view(), name='vendor_create_view'),
    url(r'^vendor/(?P<pk>\d+)/update/$', VendorUpdateView.as_view(), name='vendor_update_view'),
    url(r'^vendor/(?P<pk>\d+)/delete/$', VendorDeleteView.as_view(), name='vendor_delete_view'),
    url(r'^vendor-list/$', VendorListView.as_view(), name='vendor_list_view'),
    url(r'^manufacturer-create/$', ManufacturerCreateView.as_view(), name='manufacturer_create_view'),
    url(r'^manufacturer/(?P<pk>\d+)/update/$', ManufacturerUpdateView.as_view(), name='manufacturer_update_view'),
    url(r'^manufacturer/(?P<pk>\d+)/$', ManufacturerDeleteView.as_view(), name='manufacturer_delete_view'),
    url(r'^manufacturer-list/$', ManufacturerListView.as_view(), name='manufacturer_list_view'),
    url(r'^sales-agent-create/$', SalesAccountCreateView.as_view(), name='sales_account_create_view'),
    url(r'^sales/(?P<pk>\d+)/update/$', SalesAccountUpdateView.as_view(), name='salesaccount_update_view'),
    url(r'^sales/(?P<pk>\d+)/delete$', SalesAccountDeleteView.as_view(), name='salesaccount_delete_view'),
    url(r'^sales/(?P<pk>\d+)/$', SalesDetailView.as_view(), name='salesaccount_detail_view'),
    url(r'^sales-account-list/$', SalesListView.as_view(), name='salesaccount_list_view'),
    url(r'^sales/(?P<pk>\d+)/contracts/(?P<category>\w+)/$', SalesContractListView.as_view(), name='sales_contract_list_view'),
    url(r'^part-create/$', PartNumberCreateView.as_view(), name='part_create_view'),
    url(r'^part/(?P<pk>\d+)/edit/$', PartNumberUpdateView.as_view(), name='part_update_view'),
    url(r'^part/(?P<pk>\d+)/$', PartNumberDetailView.as_view(), name='part_detail_view'),
    url(r'^part/(?P<pk>\d+)/delete/$', PartNumberDeleteView.as_view(), name='part_delete_view'),
    url(r'^part-list/$', PartListView.as_view(), name='part_list_view'),
    url(r'^quote-create/(?P<pk>\d+)/$', QuoteCreateView.as_view(), name='quote_create_view'),
    url(r'^quote-create/$', QuoteCreateView.as_view(), name='quote_create_view_new'),
    url(r'^quote/(?P<pk>\d+)/edit/$', QuoteUpdateView.as_view(), name='quote_update_view'),
    url(r'^quote/(?P<pk>\d+)/delete/$', QuoteDeleteView.as_view(), name='quote_delete_view'),
    url(r'^quote/(?P<pk>\d+)/$', QuoteDetailView.as_view(), name='quote_detail_view'),
    url(r'^quote-list/$', QuoteListView.as_view(), name='quote_list_view'),
    url(r'^rentention-analyst/(?P<reta>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_reta'),
    url(r'^client/(?P<client>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_client'),
    url(r'^sales/(?P<agent>\d+)/login/(?P<pk>\d+)/$', UserCreateView.as_view(), name='user_create_view_sales'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rpp_test/rpp_test_tables/models.py
from django.db import models
from datetime import datetime, timedelta, timezone
from django.utils import timezone
import pytz
from simple_history.models import HistoricalRecords

class SalesAccount(models.Model):
    user = models.OneToOneField('auth.User')
    name = models.CharField(max_length=144)
    retention_analyst = models.ForeignKey('RetentionAnalyst')
    vendors = models.ManyToManyField('Vendor')
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @property
    def recent_sales(self):
        return [x for x in self.contract_set.all() if x.start_date > timezone.now().date() + timedelta(days=7)]

class Client(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    website = models.CharField(max_length=200)
    web_admin = models.CharField(max_length=100,null=True,blank=True)
    web_admin_cell = models.CharField(max_length=100,null=True,blank=True)
    correspondence_signature = models.CharField(max_length=100)
    correspondence_signature_title = models.CharField(max_length=100)
    correspondence_phone = models.CharField(max_length=100)
    correspondence_contact_one = models.CharField(max_length=100)
    correspondence_contact_two = models.CharField(max_length=100,null=True,blank=True)
    correspondence_email = models.CharField(max_length=100)
    copy_emails_to_portal_list = models.IntegerField(null=True,blank=True)
    list_discount = models.CharField(max_length=100,null=True,blank=True)
    list_discount_international = models.CharField(max_length=100,null=True,blank=True)
    service_discount = models.CharField(max_length=100,null=True,blank=True)
    override_sales_tax = models.FloatField()
    discount_off_list_percent = models.FloatField()
    rate_factor_year = models.FloatField()
    rate_factor_two_year = models.FloatField()
    rate_factor_three_year = models.FloatField()
    residual_value = models.FloatField()
    aquisition_fee = models.FloatField()
    rate_factor_increase = models.FloatField(null=True,blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_changed_by = models.CharField(max_length=100,null=True,blank=True)
    email_address_salesperson = models.CharField(max_length=100,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey('auth.User')
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    @property
    def active_sales_agents(self):
        a = []
        for con in Contract.objects.filter(client=self):
            if con.sale_agent not in a:
                a.append(con.sale_agent)
        return a

    def active_analysts(self):
        a = []
        for agent in self.active_sales_agents:
            if agent.retention_analyst not in a:
                a.append(agent.retention_analyst)
        return a

class Vendor(models.Model):
    name = models.CharField(max_length=200)
    lead_product = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    website = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Manufacturer(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    phone = models.CharField(max_length=40)
    status = models.BooleanField(default=True)
    logo = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        if self.logo:
            return self.logo.url
        return "http://images.clipartpanda.com/animated-question-mark-for-powerpoint-1256186461796715642question-mark-icon.svg.hi.png"

class PartNumber(models.Model):
    manufacturer = models.ForeignKey(Manufacturer)
    desc = models.TextField()
    end_of_service = models.DateField()
    end_of_life = models.DateField()
    end_of_support = models.DateField()
    trade_value = models.FloatField(null=True,blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.manufacturer.name +  ' ' + self.desc

class Product(models.Model):
    part_num = models.ForeignKey(PartNumber)
    serial = models.CharField(max_length=200)
    client = models.ForeignKey(Client)
    purchase_date = models.DateField()
    disposal = models.DateField(null=True,blank=True)
    service_category = models.CharField(null=True,blank=True,max_length=100)
    price = models.FloatField()
    quantity_min = models.CharField(null=True,blank=True,max_length=100)
    quantity_max = models.CharField(null=True,blank=True,max_length=100)
    duration = models.CharField(null=True,blank=True,max_length=100)
    orderability = models.CharField(null=True,blank=True,max_length=100)
    item_identifier = models.CharField(null=True,blank=True,max_length=100)
    service_program = models.CharField(max_length=100)
    category_base_discount_name = models.CharField(null=True,blank=True,max_length=100)
    end_of_sale_date = models.DateField(null=True,blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.client.name + ' ' + self.part_num.desc
    @property
    def ninety(self):
        contracts = self.contract_set.all()
        for con in contracts:
            if timezone.now().date() + timedelta(days=90) > con.end_date:
                return True
        return False

    def not_trued(self):
        contracts = self.contract_set.all()
        if contracts.count() <= 1:
            return False
        end = contracts.first().end_date
        for con in contracts:
            if con.end_date != end:
                return True
        return False

    def serv_vendor(self):
        con = self.contract_set.all().first()
        return con.vendor

    def serv_end(self):
        x = self.contract_set.all().first().end_date
        for con in self.contract_set.all():
            if con.end_date < x:
                x = con.end_date
        return x

    def has_contract(self):
        if self.contract_set.all():
            return True
        return False

    def sales_agent(self):
        return self.sales_agents()[0]

    def sales_agents(self):
        return [cont.sale_agent for cont in self.contract_set.all()]

    def ret_analyst(self):
        return [agent.retention_analyst for agent in self.sales_agents()]


class Contract(models.Model):
    client = models.ForeignKey(Client)
    product = models.ForeignKey(Product)
    contract_number = models.ForeignKey('ContractNumber')
    serial = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.FloatField()
    vendor = models.ForeignKey(Vendor)
    sale_agent = models.ForeignKey(SalesAccount)
    commission = models.FloatField(default=0)
    service_level = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200)
    site_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=200)
    country = models.CharField(max_length=100)
    quantity = models.CharField(max_length=200)
    pak_num = models.CharField(max_length=200)
    smart_net_sku = models.CharField(max_length=200,null=True,blank=True)
    smark_net_desc = models.CharField(max_length=200,null=True,blank=True)
    annual_list_price = models.CharField(max_length=200,null=True,blank=True)
    trade_value = models.CharField(max_length=200,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.client.name + self.vendor.name + str(self.cost)

    @property
    def days_left(self):
        end = self.end_date
        td =  self.end_date - timezone.now().date()
        return td.days

    def ninety(self):
        if timezone.now().date() + timedelta(days=180) > self.end_date:
            return True
        return False

    def active(self):
        if self.end_date > timezone.now().date():
            return True
        return False

    def end_of_life(self):
        return self.product.part_num.end_of_life

    def end_of_service(self):
        return self.product.part_num.end_of_service


class ClientLogin(models.Model):
    client = models.ForeignKey(Client)
    time = models.DateTimeField(auto_now_add=True)

class SalesAccountLogin(models.Model):
    agent = models.ForeignKey(SalesAccount)
    time = models.DateTimeField(auto_now_add=True)

class AdminLogin(models.Model):
    admin = models.ForeignKey('auth.user')
    time = models.DateTimeField(auto_now_add=True)

# class AdminChange(model.Model):
#     admin = models.ForeignKey('auth.user')
#     time = models.DateTimeField(auto_now_add=True)

class RetentionAnalyst(models.Model):
    name = models.CharField(blank=True,null=True,max_length=100)
    email = models.CharField(max_length=100)
    user = models.OneToOneField('auth.User')

    def __str__(self):
        return str(self.name)

    @property
    def contract_count(self):
        return len([x for x in Contract.objects.all() if x.sale_agent.retention_analyst == self])


class ClientUser(models.Model):
    user = models.OneToOneField('auth.user')
    client = models.ForeignKey(Client)

rpp_test/templates/admin_dashboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <style media="screen">
      form ul {
        display: none;
      }
    </style>

    <script
  src="https://code.jquery.com/jquery-3.2.1.slim.js"
  integrity="sha256-tA8y0XqiwnpwmOIl3SGAcFl2RvxHjA8qp0+1uCGmRmg="
  crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen" title="no title">
    <link rel="stylesheet" href="{% static 'css/admin_dash.css' %}" media="screen" title="no title">
    <meta charset="utf-8">
    <title></title>
  </head>

  <body>

      <div id="wrapper" class="toggled">


          <!-- Sidebar -->
          <div id="sidebar-wrapper">
              <ul class="sidebar-nav">
                  <li class="sidebar-brand">
                      <a href="#">
                          Settings
                      </a>
                  </li>
                  <li>
                      <a href="#">Administration</a>
                      <ul style="color:white;">
                        <li><a id="contractList" href="#contractList">Contracts</a></li>
                        <li><a id="manufacturerList" href="#manufacturerList">Manufacturers</a></li>
                        <li><a id="vendorList" href="#vendor-list">Vendors</a></li>
                        <li><a id="retentionList" href="#retentionList">Retention Analysts</a></li>
                        <li><a id="salesList" href="#salesList">Sales</a></li>
                        <li><a id="productList" href="#productList">Products</a></li>
                        <li><a id="clientList" href="#clientList">Clients</a></li>
                        <li><a id="partList" href="#partList">Parts</a></li>
                      </ul>
                  </li>
                  <li>
                      <a href="#">Security</a>
                      <ul>
                        <li>User Admin</li>
                        <li>Group Admin</li>
                      </ul>
                  </li>
                  <li>
                      <a href="#">Tools</a>
                      <ul>
                        <li>Logs</li>
                        <li>Bulk Import</li>
                      </ul>
                  </li>
                  <li>
                      <a href="#">Appearence</a>
                  </li>
                  <li>
                      <a href="#">Placeholder</a>
                  </li>
                  <li>
                      <a href="#">Placeholder</a>
                  </li>
                  <li>
                      <a href="#">Placeholder</a>
                  </li>
              </ul>
          </div>
          <!-- /#sidebar-wrapper -->

          <!-- Page Content -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{% url 'login' %}">Home Page</a></li>
        <li><a href="{% url 'admin:index' %}">Django Admin</a></li>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

          <div id="page-content-wrapper">
              <div class="container-fluid">
                <h1>Dashboard</h1>
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                  <div class="row twenty">
                      <div class="col-lg-3 col-md-6">
                        <div style="" class="panel panel-primary">
                          <div class="panel-heading">
                            <div class="row">
                              <div class="col-xs-8">
                                New Clients
                              </div>
                              <div class="col-xs-4">
                                {{ new_clients }}
                              </div>
                            </div>
                          </div>

                          <div class="panel-footer">
                            <!-- <a id="" href="#test1">Details</a> -->
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6">
                        <div style="" class="red panel panel-primary">
                          <div class="red panel-heading">
                            <div class="row">
                              <div class="col-xs-8">
                                True Up Ops
                              </div>
                              <div class="col-xs-4">
                                {{ trueups|length }}
                              </div>
                            </div>
                          </div>
                          <a href="#">
                          <div class="panel-footer">
                            <!-- <a id="test2" href="#test2">Details</a> -->
                          </div></a>
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6">
                        <div style="" class="green panel panel-primary">
                          <div class="green panel-heading">
                            <div class="row">
                              <div class="col-xs-8">
                                Sales Today
                              </div>
                              <div class="col-xs-4">
                                {{ sales_today }}
                              </div>
                            </div>
                          </div>
                          <a href="#">
                          <div class="panel-footer">
                            <!-- <a id="test3" href="#test3">Details</a> -->
                          </div></a>
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6">
                        <div style="" class="orange panel panel-primary">
                          <div class="orange panel-heading">
                            <div class="row">
                              <div class="col-xs-8">
                                Exp. Contracts
                              </div>
                              <div class="col-xs-4">
                                {{ ninety_contracts|length }}
                              </div>
                            </div>
                          </div>
                          <a href="#">
                          <div class="panel-footer">
                            <!-- <a id="test4" href="#test4">Details</a> -->
                          </div></a>
                        </div>
                      </div>

                  </div>

                  <div id="productListDiv" class="hidden">
                    {% include 'partials/admin_dash/sidebar/product_list.html' %}
                  </div>
                  <div id="contractListDiv" class="hidden">
                    {% include 'partials/admin_dash/contract_list.html' %}
                  </div>
                  <div id="salesListDiv" class="hidden">
                    {% include 'partials/admin_dash/sidebar/sales_list.html' %}
                  </div>
                  <div id="retentionListDiv" class="hidden">
                    {% include 'partials/admin_dash/sidebar/_reta.html' %}
                  </div>
                  <div id="vendorListDiv" class='hidden'>
                    {% include 'partials/admin_dash/sidebar/vendor_list.html' %}
                  </div>
                  <div id="manufacturerListDiv" class='hidden'>
                    {% include 'partials/admin_dash/sidebar/manufacturer_list.html' %}
                  </div>
                  <div id="clientListDiv" class='hidden'>
                    {% include 'partials/admin_dash/sidebar/client_list.html' %}
                  </div>
                  <div id="partListDiv" class='hidden'>
                    {% include 'partials/admin_dash/sidebar/part_list.html' %}
                  </div>


              </div>
          </div>
          <!-- /#page-content-wrapper -->

      </div>
      <!-- /#wrapper -->

      <!-- jQuery -->
      <script src="js/jquery.js"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="js/bootstrap.min.js"></script>

      <!-- Menu Toggle Script -->



{% include 'partials/admin_dash/adminjs.html' %}


</body>
</html>

rpp_test/templates/sales_client_list.html
{% extends 'partials/new_dash/sales_base.html' %}

{% block content %}

<div style="font-size:18px;border-bottom:1px solid black;margin-bottom:10px;" class="row">
  <div class="col-md-2">Name</div>
  <div class="col-md-2">Lead Product</div>
  <div class="col-md-2">Website</div>
  <div class="col-md-3">
    <div class="col-md-5">City</div>
    <div class="col-md-3">State</div>
    <div class="col-md-2">Country</div>
  </div>
  <div class="col-md-1">Contracts</div>
  <div class="col-md-2">Products</div>
</div>
{% for client in clients %}
<div class="con-item">
<a href="{% url 'client_detail_view' client.id %}">
  <div class="row">
    <div class="col-md-2">{{ client.name }}</div>
    <div class="col-md-2">{{ client.lead_product }}</div>
    <div class="col-md-2">{{ client.website }}</div>
    <div class="col-md-3">
      <div class="col-md-6">{{ client.city }}</div>
      <div class="col-md-2">{{ client.state }}</div>
      <div class="col-md-2">{{ client.country }}</div>
    </div>
    <div class="col-md-1">{{ client.contract_set.all.count }}</div>
    <div class="col-md-2">{{ client.product_set.all.count }}</div>
  </div>
</a>
</div>
{% endfor %}
{% endblock %}